spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mariadb://localhost:3306/zupcar
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    url: jdbc:mariadb://localhost:3306/zupcar
    user: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWD:root}
    enabled: true

server:
  error:
    include-message: always